apiVersion: v1
kind: Service
metadata:
  name: fleetprivacy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
{{- if .Values.service.internal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- end }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: fleetprivacy
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
