apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetprivacy-api
  labels:
    app.kubernetes.io/name: fleetprivacy
    app.kubernetes.io/component: api
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleetprivacy-worker
  labels:
    app.kubernetes.io/name: fleetprivacy
    app.kubernetes.io/component: worker
automountServiceAccountToken: true
